### ISSUE TITLE
Exit status

### ISSUE THREAD

**Issue by kurz-m** [RealConrad/42minishell#40]
## Get correct exit status

During testing, I encountered some _inconsistencies_ regarding the exit status code.

```bash
minishell: syntax error near unexpected token |
minishell> echo $?
258
```
This should not give 258 as return value. It should return *2*

`ctrl+c` returns _0_ as exit status, but should return _130_.

```bash
minishell> "
minishell: unclosed quotes 
minishell> echo $?
0
```
returns _0_ as exit status but should also return _2_.

**Comment by RealConrad** [comment]
Thank you! We will look into it :D

**Comment by kurz-m** [comment]
## Addition
You actually have the correct exit code when using `ctrl+c` in a blocking child command:
```bash
minishell> cat
# pressing ctrl+c
minishell> echo $?
130
```
Calling the cat command and then pressing `ctrl+c` gives the correct exit status of 130.
