### ISSUE TITLE
No collapsing pipes

### ISSUE THREAD

**Issue by kurz-m** [RealConrad/42minishell#41]
## Collapsing pipes

try the following command in bash and then in your shell:

```bash
cat /dev/urandom | ls

# or

cat /dev/random | ls
```

You will see that your shell is continuously waiting for the EOF of _/dev/random/_ which will never be reached and therefore your shell is getting unusable. In that scenario, your pipe should collapse  and also close the filestream from `cat /dev/random`.

**Comment by RealConrad** [comment]
Fixed bug. We now only waitpid() for the last pipe, where as previously we would wait for every pipe/child process.
